# site information
title: Kison He
description: UESTC RM Anime
url: https://kisonhe.github.io/
author: Kison He
email: kisonhe@outlook.com
logo: /asset/icon/logo.png # url of your logo or avatar
lang: zh-hans # language-territory
color: '#7B90D2'


social:
  name: Kison He
  links:
    - https://github.com/KisonHe/

webmaster_verifications:
  bing:
  google:
  yandex:

# comment
github-issue: 'KisonHe/kisonhe.github.io' # github username/repository, e.g. 'username/repository'
disqus: # disqus shortname
livere: # livere data-uid

comment:
  vssue:
    state: true
    owner: KisonHe
    repo: kisonhe.github.io
    clientID: 794cb5f9ffa2f03fd819
    clientSecret: 70e86f29c417b05aea80840c8fdf392ed8b572d8
  disqus: # disqus shortname
  livere: # livere data-uid


# analytic
google_analytics: # google analytics web tracking code

# jekyll config
permalink: /:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

include:
  - analytics.html

exclude:
  - cname
  - gemfile
  - gemfile.lock
  - license.txt
  - readme.md
  - vendor
