# site information
title: Kison He
description: USETC RM Anime
url: https://blog.kisonhe.xyz
author: Kison He
email: kisonhe@outlook.com
logo: /asset/icon/logo.png # url of your logo or avatar
lang: zh-hans # language-territory
theme-color: '#dc9fb4'
feed: true

social:
  name: Kison He
  links:
    - https://github.com/KisonHe/

comment:
  vssue:
    state: true
    owner: KisonHe
    repo: kisonhe.github.io
    clientID: 794cb5f9ffa2f03fd819
    clientSecret: 70e86f29c417b05aea80840c8fdf392ed8b572d8
  disqus: # disqus shortname
  livere: # livere data-uid

analytic:
  google: # web tracking code

# jekyll config
permalink: /:title/

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

plugins:
  - jekyll-sitemap

include:

exclude:
  - cname
  - gemfile
  - gemfile.lock
  - license.txt
  - readme.md
